dependency:
  licenses:
    - type: go
      name: github.com/keighl/mandrill
      version: v0.0.0-20170605120353-1775dd4b3b41
      license: [BSD-3-Clause]
    - name: github.com/modfin/brev        # modfin
      type: go