FROM golang:1.23.6-alpine as builder

COPY . /mmailer
WORKDIR /mmailer
RUN go mod download
RUN go build -o /mmailerd cmd/mmailerd/mmailerd.go

FROM --platform=linux/amd64 alpine:3.21.3

RUN apk add --no-cache tzdata ca-certificates
EXPOSE 8080
RUN addgroup --system --gid 7005 mmailer && adduser --system --uid 7005 --shell /usr/sbin/nologin --ingroup mmailer mmailer

USER mmailer:mmailer
COPY --from=builder /mmailerd /
CMD /mmailerd