FROM golang:1.19.2-alpine3.16 as builder

RUN apk add --no-cache git curl build-base bash shadow

RUN mkdir -p /go/src/mmailer
WORKDIR /go/src/mmailer

COPY . /go/src/mmailer

RUN ls

RUN go build -o /mmailerd ./cmd/mmailerd/mmailerd.go

FROM alpine:3.16.2
RUN apk add --no-cache tzdata ca-certificates
EXPOSE 8080
COPY --from=builder /mmailerd /
CMD /mmailerd
