FROM golang:1.19.2

RUN go get -u -v github.com/codeskyblue/fswatch


RUN mkdir -p /go/src/github.com/modfin/mmailer
WORKDIR /go/src/github.com/modfin/mmailer

EXPOSE 8080

# run fswatch
CMD fswatch -config /fsw.yml