FROM golang:1.23.6
RUN go install github.com/codeskyblue/fswatch@v0.0.0-20200812032752-892e1e55b602


RUN mkdir -p /go/src/github.com/modfin/mmailer
WORKDIR /go/src/github.com/modfin/mmailer

EXPOSE 8080

# run fswatch
CMD fswatch -config /fsw.yml