desc: re builds go
triggers:
  - name: ''
    pattens:
      - '**/*.go'
    env:
      DEBUG: '1'
    cmd: cd /go/src/spidercave/mmailer && go run ./cmd/mmailerd/mmailerd.go serve
    shell: true
    delay: 1000ms
    stop_timeout: 5000ms
    signal: SIGTERM
    kill_signal: 'SIGTERM'
watch_paths:
  - .
watch_depth: 10